# Generated by Django 3.1.5 on 2021-04-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
